//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Commande = new HashSet<Commande>();
        }
    
        public long IdentifiantClient { get; set; }
        public Nullable<long> ReferenceDuClient { get; set; }
        public string NomDuClient { get; set; }
        public string PrenomDuClient { get; set; }
        public Nullable<long> Coefficient { get; set; }
        public string AdresseDuClient { get; set; }
        public string VilleDuClient { get; set; }
        public Nullable<long> CodePostalDuClient { get; set; }
        public string AdresseMailDuClient { get; set; }
        public Nullable<long> TelephoneDuClient { get; set; }
        public Nullable<long> IdentifiantServiceCommercial { get; set; }
    
        public virtual Service_Commercial Service_Commercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commande { get; set; }
    }
}
