//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.contenir = new HashSet<contenir>();
            this.Livraison = new HashSet<Livraison>();
        }
    
        public long IdentifiantCommande { get; set; }
        public Nullable<long> NumeroDeCommande { get; set; }
        public Nullable<System.DateTime> DateDeCommande { get; set; }
        public string AdresseDeLivraison { get; set; }
        public string VilleDeLivraison { get; set; }
        public string CodePostalDeLivraison { get; set; }
        public Nullable<decimal> PrixTotalCommande { get; set; }
        public string AdresseDeFacturation { get; set; }
        public string VilleDeFacturation { get; set; }
        public long CodePostalDeFacturation { get; set; }
        public Nullable<long> IdentifiantClient { get; set; }
        public Nullable<long> NumeroFacture { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Facture Facture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contenir> contenir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livraison> Livraison { get; set; }
    }
}
