//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fournisseur()
        {
            this.vendre = new HashSet<vendre>();
        }
    
        public long IdentifiantFournisseur { get; set; }
        public Nullable<bool> Importateur { get; set; }
        public string NomDuFournisseur { get; set; }
        public string AdresseDuFournisseur { get; set; }
        public string VilleDuFournisseur { get; set; }
        public Nullable<long> CodePostalDuFournisseur { get; set; }
        public string AdresseMailDuFournisseur { get; set; }
        public Nullable<long> TelephoneDuFournisseur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendre> vendre { get; set; }
    }
}
