//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fil_rougeEntities : DbContext
    {
        public fil_rougeEntities()
            : base("name=fil_rougeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<composer> composer { get; set; }
        public virtual DbSet<contenir> contenir { get; set; }
        public virtual DbSet<Facture> Facture { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Livraison> Livraison { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<RubriqueDuProduit> RubriqueDuProduit { get; set; }
        public virtual DbSet<Service_Commercial> Service_Commercial { get; set; }
        public virtual DbSet<vendre> vendre { get; set; }
    }
}
