//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.composer = new HashSet<composer>();
            this.contenir = new HashSet<contenir>();
            this.vendre = new HashSet<vendre>();
        }
    
        public long IdentifiantProduit { get; set; }
        public string LibelleCourtDuProduit { get; set; }
        public string LibelleLongDuProduit { get; set; }
        public string PhotoDuProduit { get; set; }
        public Nullable<decimal> PrixDachatDuProduit { get; set; }
        public Nullable<bool> ProduitActif { get; set; }
        public Nullable<decimal> PrixHorsTaxe { get; set; }
        public Nullable<long> TVA { get; set; }
        public Nullable<long> IdentifiantRubrique { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<composer> composer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contenir> contenir { get; set; }
        public virtual RubriqueDuProduit RubriqueDuProduit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vendre> vendre { get; set; }
    }
}
