//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RubriqueDuProduit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RubriqueDuProduit()
        {
            this.Produit = new HashSet<Produit>();
            this.RubriqueDuProduit1 = new HashSet<RubriqueDuProduit>();
        }
    
        public long IdentifiantRubrique { get; set; }
        public string NomRubrique { get; set; }
        public Nullable<long> Rubrique_principale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit> Produit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RubriqueDuProduit> RubriqueDuProduit1 { get; set; }
        public virtual RubriqueDuProduit RubriqueDuProduit2 { get; set; }
    }
}
